Minor additions - mainly to support listening to news
dodoadoodoo/kodi-sverigesradio pull request #2
Opened 2019-03-03 12:22 UTC by bjorneg

- Added paging (Im a newsbuff and Ekot has too many episodes to be handled without paging)
- Added content type. Content type enables a description of
  each program to be displayed in the left screen area.
- Added selectable date+time prefix of each program (again - to know which episode of eg ekot to listen to

2019-03-12 14:36 UTC, dodoadoodoo commented on addon.py
> +from xbmcswift2 import Plugin,  xbmcgui
Is the xbmcgui import needed?

2019-03-12 14:38 UTC, dodoadoodoo commented on addon.py
> +        print file
Change to log statement and remove print.

2019-03-12 14:40 UTC, dodoadoodoo requested changes
Thanks for this. See some minor comments inline. 

Do you think you are able to separate this into one PR for removing the sports stuff and an additional for the paging and date stuff?

2019-03-16 08:35 UTC, bjorneg commented
Current commit is the removal of sports broadcats, league, teams change only.
I will create a separate PR for the other stuff

2019-03-16 11:47 UTC, bjorneg commented
Current commit is the removal of sports broadcats, league, teams change only.
I will create a separate PR for the other stuff

2019-03-16 11:48 UTC, bjorneg commented
Im obviously not that good at git & github - however, now there is two (relevant) commits:
- removal of sport etc
- addition of paging, etc
OK?

2019-03-20 08:49 UTC, dodoadoodoo commented
Thanks. Kinda busy with life, will take a closer look any old day now...

2019-12-08 15:14 UTC, merged